repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
    name: Check for files larger than 5 MB
    args: [ "--maxkb=5120" ]
  - id: end-of-file-fixer
    name: Check for a blank line at the end of scripts (auto-fixes)
  - id: trailing-whitespace
    name: Check for trailing whitespaces (auto-fixes)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.3
  hooks:
  - id: ruff-format
    name: ruff formatter
    #exclude: test_example_module.py|run_pipeline.py
  - id: ruff
    args: [ --fix ]
    name: ruff linter
    #exclude: test_example_module.py|run_pipeline.py
